services:
  - type: web
    name: django-site
    env: python
    rootDir: mysite
    buildCommand: ./build.sh
    startCommand: poetry run gunicorn mysite.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_ENV
        value: production
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: 127.0.0.1,localhost
