# Generated by Django 6.0.3 on 2026-03-13 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_question_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="choice",
            options={"verbose_name": "Choice", "verbose_name_plural": "Choices"},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"verbose_name": "Question", "verbose_name_plural": "Questions"},
        ),
    ]
